#
# common tasks needed by other roles
# Author: Linou.Zhang
#

---
- name: Config HDP repo
  shell: "wget -nv http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.6.1.0/hdp.repo -O /etc/yum.repos.d/hdp.repo creates=/etc/yum.repos.d/hdp.repo"
  sudo: yes

- name: Download JDK
  shell: "wget -c --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ jdk_download_url }}  -O {{ jdk_rpm }} creates={{ jdk_rpm }} "

- name: Install JDK
  shell: "yum -y --nogpgcheck localinstall {{ jdk_rpm }} creates=/usr/java"
  sudo: yes

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable SELinux in conf file
  selinux:
     state: disabled
