#
# Tasks to install common tools
# Author: Linou.Zhang
#
---
- name: download epel rpm
  shell: "wget --no-check-certificate {{ epel_url }} -O {{ epel_rpm }} creates={{ epel_rpm }}"

- name: yum install epel (Extra Packages for Enterprise Linux)
  shell: "yum -y --nogpgcheck localinstall {{ epel_rpm }}"
  sudo: yes

- name: git
  yum: name='git' state=installed
  sudo: yes

- name: yum install python-pip
  yum: name='python-pip' state=installed
  sudo: yes

#- name: easy_install

#- name: install pip
  #easy_install: name='pip'
  #sudo: yes

- name: install argparse for python
  pip: name='argparse' state=present
  sudo: yes

- name: install tmux
  yum: name='tmux' state=installed
  sudo: yes

- name: install lsof
  yum: name='lsof' state=installed
  sudo: yes

- name: download maven repo
  shell: "wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo"
  sudo: yes

- name: install maven
  yum: name='apache-maven' state=installed
  sudo: yes

