#
# Handlers for the hadoop master services
# Author: Hikmat Dhamee
#

---
# Start HDFS
- name: format the namenode
  shell: creates=/usr/lib/hadoop/namenode.formatted su - hdfs -c "hadoop namenode -format" && touch /usr/lib/hadoop/namenode.formatted
  sudo: yes

- name: start hadoop namenode services
#  service: name=hadoop-hdfs-namenode state=started
  shell: "su - hdfs -c '/usr/hdp/current/hadoop-client/sbin/hadoop-daemon.sh start namenode' "
  sudo: yes

- name: Start HDFS on datanodes
#  service: name=hadoop-hdfs-datanode state=started
  shell: "su - hdfs -c '/usr/hdp/current/hadoop-client/sbin/hadoop-daemon.sh start datanode' "
  sudo: yes

# Start MapReduce.
- name: Start Resource Manager
#  service: name=hadoop-yarn-resourcemanager state=started
  shell: "su - hdfs -c '/usr/hdp/current/hadoop-yarn-client/sbin/yarn-daemon.sh start resourcemanager' "
  sudo: yes

- name: Start Node Manager on datanodes
#  service: name=hadoop-yarn-nodemanager state=started
  shell: "su - hdfs -c '/usr/hdp/current/hadoop-yarn-client/sbin/yarn-daemon.sh start nodemanager' "
  sudo: yes

- name: Start History Server
#  service: name=hadoop-mapreduce-historyserver state=started
  shell: "su - hdfs -c '/usr/hdp/current/hadoop-mapreduce-client/sbin/mr-jobhistory-daemon.sh start historyserver' "
  sudo: yes
